#!/usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx',
    source=bld.path.ant_glob('*.cpp'),
    target='usb_device_hotplug',
    use=['hotplug'],
    uselib=['LIBUDEV', 'PTHREAD'])
